# Generated by Django 5.0.4 on 2024-04-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'NOT STARTED'), (2, 'WORKING ON'), (3, 'TESTING'), (4, 'FINISHED')], default='STATUS_TODO'),
        ),
    ]
